# Build configuration for ML Heating multiarch container
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-alpine3.18
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-alpine3.18
args: {}
labels:
  org.opencontainers.image.title: "ML Heating Control"
  org.opencontainers.image.description: "Physics-based machine learning heating control system"
  org.opencontainers.image.source: "https://github.com/helgeerbe/ml_heating"
  org.opencontainers.image.licenses: "MIT"
